- name: install and start mysql
  hosts: web
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysqld
      state: present
  - name: start mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes


